version: '3.8'
services:

  app:
    image: planner-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://planningProjectDB:5432/planningProject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: planningProjectDB
    environment:
      POSTGRES_DB: planningProject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"

  nginx:
    image: angular-frontend
    ports:
      - "80:80"
    depends_on:
      - app

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  minio_data: