version: '3.8'
services:

  app:
    image: planner-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/PlanningProjectDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
    ports:
      - "8080:8080"

  nginx:
    image: angular-frontend
    ports:
      - "80:80"
    depends_on:
      - app